# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  install:
    desc: Installs the dependencies.
    cmds:
      - poetry install
  lint:
    desc: Lints the code and reports on issues.
    cmds:
      - poetry run black --check weather_data_fetcher.py
      - |
        poetry run flake8 weather_data_fetcher.py \
          --show-source \
          --statistics \
          --count
      - poetry run pylint weather_data_fetcher.py

  run:
    desc: Run the Weather Data Fetcher
    cmds: 
      - poetry run python weather_data_fetcher.py

  test:
    desc: Runs tests on the code
    cmds:
      - >
        poetry run pytest
        -s
        --cov=.
        --cov-report=html